name: .NET 4.6 + Pack + Push no NuGet

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./DotEnvControl/DotEnvControl.csproj

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 4.6
      uses: actions/setup-dotnet@v1

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push ./DotNetControl/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
